name: MyPepTracker
options:
  bundleIdPrefix: com.greg.roy
  deploymentTarget:
    iOS: "26.0"
settings:
  base:
    SWIFT_VERSION: "6.0"
    DEVELOPMENT_TEAM: ""
schemes:
  MyPepTracker:
    build:
      targets:
        MyPepTracker: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - MyPepTrackerTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
targets:
  MyPepTracker:
    type: application
    platform: iOS
    sources:
      - MyPepTracker
    resources:
      - MyPepTracker/Resources
    settings:
      base:
        INFOPLIST_KEY_CFBundleDisplayName: MyPepTracker
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
  MyPepTrackerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - MyPepTrackerTests
    dependencies:
      - target: MyPepTracker
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
